---
# Ansible playbook to provision a Raspberry Pi for the E-Nose project:
# installs base packages, sets hostname, configures SSH, installs uv, clones
# the repo, installs dependencies, provisions InfluxDB, writes credentials,
# and configures I2C with a reboot handler.

- name: Setup Raspberry Pi 4/5 für E-Nose Projekt
  hosts: "192.168.0.21"
  remote_user: "david"
  become: yes
  vars:
    ansible_user: "david"
    ansible_python_interpreter: "/usr/bin/python3.13"
    project_dir: "/home/{{ ansible_user }}/e-nose-project"
    pi_hostname: "e-nose"
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINBJoA3dighAPvYOLt1im8PYSh2WxL9TBhjeMkdXCklR david@desktop"
    
    # --- InfluxDB Konfiguration ---
    influx_user: "admin"
    influx_password: "enose_secret_password"  # Nach Setup ändern!
    influx_org: "enose_org"
    influx_bucket: "sensor_data"
    influx_retention: 0 # 0 = infinite (seconds)

  tasks:
    # ---------------------------------------------------------
    # Block 1: System-Grundlagen & Pakete
    # ---------------------------------------------------------
    - name: "System: Packages & Updates"
      block:
        - name: System-Pakete aktualisieren
          ansible.builtin.apt:
            update_cache: yes
            upgrade: dist

        - name: Notwendige System-Pakete installieren
          ansible.builtin.apt:
            pkg:
              - i2c-tools
              - git
              - curl
              - wget
              - gpg
              - build-essential
              - kitty-terminfo
              - python3-dev  # Python.h für C-Extensions (sysv-ipc, etc.)
            state: present

        - name: User zur i2c und gpio Gruppe hinzufügen
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: i2c,gpio
            append: yes

        - name: Hostname setzen
          ansible.builtin.hostname:
            name: "{{ pi_hostname }}"

        - name: Hostname in /etc/hosts eintragen
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: '^127\.0\.1\.1\s+'
            line: "127.0.1.1 {{ pi_hostname }}"
            state: present
      tags: packages

    # ---------------------------------------------------------
    # Block 2: SSH Key Setup
    # ---------------------------------------------------------
    - name: "System: SSH Access"
      block:
        - name: SSH Verzeichnis erstellen
          ansible.builtin.file:
            path: "/home/{{ ansible_user }}/.ssh"
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0700'

        - name: Authorized Key hinzufügen
          ansible.builtin.lineinfile:
            path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
            line: "{{ ssh_key }}"
            create: yes
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0600'
      tags: ssh

    # ---------------------------------------------------------
    # Block 3: UV Installation
    # ---------------------------------------------------------
    - name: "Tools: UV Setup"
      block:
        - name: Prüfen ob UV bereits installiert ist
          ansible.builtin.stat:
            path: /usr/local/bin/uv
          register: uv_installed

        - name: UV Archiv für aarch64 herunterladen
          ansible.builtin.get_url:
            url: "https://github.com/astral-sh/uv/releases/latest/download/uv-aarch64-unknown-linux-gnu.tar.gz"
            dest: "/tmp/uv.tar.gz"
            mode: '0644'
          when: not uv_installed.stat.exists

        - name: UV Archiv entpacken
          ansible.builtin.unarchive:
            src: "/tmp/uv.tar.gz"
            dest: "/tmp"
            remote_src: yes
          when: not uv_installed.stat.exists

        - name: UV Binaries nach /usr/local/bin kopieren
          ansible.builtin.copy:
            src: "/tmp/uv-aarch64-unknown-linux-gnu/{{ item }}"
            dest: "/usr/local/bin/{{ item }}"
            mode: '0755'
            remote_src: yes
          loop:
            - uv
            - uvx
          when: not uv_installed.stat.exists

        - name: Temporäre Dateien löschen
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "/tmp/uv.tar.gz"
            - "/tmp/uv-aarch64-unknown-linux-gnu"
          when: not uv_installed.stat.exists
      tags: uv

    # ---------------------------------------------------------
    # Block 4: Project Setup
    # ---------------------------------------------------------
    - name: "Project: Git Clone & Init"
      block:
        - name: Prüfen ob Projekt bereits existiert
          ansible.builtin.stat:
            path: "{{ project_dir }}/.git"
          register: repo_exists

        - name: Repository klonen (nur wenn nicht vorhanden)
          ansible.builtin.git:
            repo: 'https://github.com/NoahRau/E-Nose.git'
            dest: "{{ project_dir }}"
            version: main
          become: yes
          become_user: "{{ ansible_user }}"
          when: not repo_exists.stat.exists

        - name: Repository aktualisieren (git pull)
          ansible.builtin.command:
            cmd: git pull --ff-only
            chdir: "{{ project_dir }}"
          become: yes
          become_user: "{{ ansible_user }}"
          when: repo_exists.stat.exists
          register: git_pull
          changed_when: "'Already up to date' not in git_pull.stdout"
          failed_when: false  # Don't fail on local changes

        - name: UV Sync (Dependencies installieren)
          ansible.builtin.command:
            cmd: /usr/local/bin/uv sync
            chdir: "{{ project_dir }}"
          become: yes
          become_user: "{{ ansible_user }}"
          environment:
            # Stelle sicher, dass uv im Pfad gefunden wird, auch wenn wir User wechseln
            PATH: "/usr/local/bin:/usr/bin:/bin"
      tags: project

    # ---------------------------------------------------------
    # Block 5: InfluxDB Installation & Setup
    # ---------------------------------------------------------
    - name: "Database: InfluxDB"
      block:
        - name: InfluxDB Keyring Verzeichnis
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: InfluxDB GPG Key herunterladen
          ansible.builtin.get_url:
            url: https://repos.influxdata.com/influxdata-archive.key
            dest: /tmp/influxdata-archive.key
            mode: '0644'

        - name: GPG Key Fingerprint verifizieren und installieren
          ansible.builtin.shell: |
            gpg --show-keys --with-fingerprint --with-colons /tmp/influxdata-archive.key 2>&1 | \
            grep -q '^fpr:\+24C975CBA61A024EE1B631787C3D57159FC2F927:$' && \
            cat /tmp/influxdata-archive.key | gpg --dearmor | tee /etc/apt/keyrings/influxdata-archive.gpg > /dev/null
          args:
            creates: /etc/apt/keyrings/influxdata-archive.gpg

        - name: InfluxDB Repository definieren
          ansible.builtin.copy:
            dest: /etc/apt/sources.list.d/influxdata.list
            content: |
              deb [signed-by=/etc/apt/keyrings/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main

        - name: Cache Update nach Repo-Add
          ansible.builtin.apt:
            update_cache: yes

        - name: InfluxDB & CLI installieren
          ansible.builtin.apt:
            pkg:
              - influxdb2
              - influxdb2-cli
            state: present

        - name: InfluxDB Service starten
          ansible.builtin.service:
            name: influxdb
            state: started
            enabled: yes

        - name: Warte auf Port 8086
          ansible.builtin.wait_for:
            port: 8086
            delay: 5

        # Check Setup State
        - name: Prüfen ob InfluxDB bereits konfiguriert ist
          ansible.builtin.uri:
            url: http://localhost:8086/api/v2/setup
            method: GET
            return_content: yes
          register: influx_setup_status
          failed_when: false

        - name: InfluxDB initial setup (via API)
          ansible.builtin.uri:
            url: http://localhost:8086/api/v2/setup
            method: POST
            body_format: json
            body:
              username: "{{ influx_user }}"
              password: "{{ influx_password }}"
              org: "{{ influx_org }}"
              bucket: "{{ influx_bucket }}"
              retentionPeriod: "{{ influx_retention }}" # seconds; 0 = infinite
            status_code: 201
          register: setup_result
          when: influx_setup_status.json.allowed == true

        # Token Retrieval (Only if we just set it up, otherwise this is tricky without admin token)
        # Note: If setup ran previously, we assume token is lost or user handles it. 
        # This block extracts the token from the FRESH setup response.
        
        - name: Token aus Setup-Response extrahieren
          ansible.builtin.set_fact:
            admin_token: "{{ setup_result.json.auth.token }}"
          when: setup_result.changed

        - name: Admin Token anzeigen (Nur bei Erst-Setup)
          ansible.builtin.debug:
            msg: "Neuer Admin Token: {{ admin_token }}"
          when: setup_result.changed

        - name: Projekt-Ordner für Credentials
          ansible.builtin.file:
            path: "{{ project_dir }}"
            state: directory
            owner: "{{ ansible_user }}"
            mode: '0755'
          when: setup_result.changed

        - name: Credentials Datei speichern
          ansible.builtin.copy:
            dest: "{{ project_dir }}/INFLUX_CREDENTIALS.md"
            owner: "{{ ansible_user }}"
            content: |
              # InfluxDB Zugangsdaten
              Generiert am: {{ ansible_date_time.iso8601 }}

              ## Login
              - **URL:** http://localhost:8086
              - **User:** {{ influx_user }}
              - **Org:** {{ influx_org }}
              - **Bucket:** {{ influx_bucket }}

              ## Admin Token
              ```
              {{ admin_token }}
              ```
          when: setup_result.changed

        - name: Influx Token in config.py setzen (nur Erst-Setup)
          ansible.builtin.lineinfile:
            path: "{{ project_dir }}/DataAcquisition/src/DataAcquisition/config.py"
            regexp: '^INFLUX_TOKEN = '
            line: 'INFLUX_TOKEN = "{{ admin_token }}"'
          become: yes
          become_user: "{{ ansible_user }}"
          when: setup_result is defined and setup_result.changed

      tags: influx

    # ---------------------------------------------------------
    # Block 6: Hardware (I2C & GPIO)
    # ---------------------------------------------------------
    - name: "Hardware: I2C Config"
      block:
        # Disable hardware I2C (causes clock stretching issues with SCD30)
        - name: Hardware I2C deaktivieren (dtparam=i2c_arm)
          ansible.builtin.lineinfile:
            path: /boot/firmware/config.txt
            regexp: '^dtparam=i2c_arm='
            line: '#dtparam=i2c_arm=on'
            state: present
          notify: Reboot Raspberry Pi

        - name: Hardware I2C baudrate deaktivieren
          ansible.builtin.lineinfile:
            path: /boot/firmware/config.txt
            regexp: '^dtparam=i2c_arm_baudrate='
            line: '#dtparam=i2c_arm_baudrate=50000'
            state: present
          notify: Reboot Raspberry Pi

        # Use software/bitbanged I2C via GPIO overlay (more reliable for SCD30)
        - name: Software I2C Overlay aktivieren (GPIO bitbang)
          ansible.builtin.lineinfile:
            path: /boot/firmware/config.txt
            regexp: '^dtoverlay=i2c-gpio'
            line: 'dtoverlay=i2c-gpio,bus=1,i2c_gpio_sda=2,i2c_gpio_scl=3,i2c_gpio_delay_us=20'
            state: present
          notify: Reboot Raspberry Pi

        - name: I2C Kernel Module laden
          community.general.modprobe:
            name: i2c-dev
            state: present
      tags: hardware

    # ---------------------------------------------------------
    # Block 7: GPIO Libraries (Pi4/Pi5 compatibility)
    # ---------------------------------------------------------
    - name: "Hardware: GPIO Libraries"
      block:
        - name: Raspberry Pi Model ermitteln
          ansible.builtin.command: cat /proc/device-tree/model
          register: pi_model
          changed_when: false

        - name: Pi Model anzeigen
          ansible.builtin.debug:
            msg: "Detected: {{ pi_model.stdout }}"

        # Set extra flag based on Pi model
        - name: GPIO extra für Pi5 setzen
          ansible.builtin.set_fact:
            gpio_extra: "pi5"
          when: "'Raspberry Pi 5' in pi_model.stdout"

        - name: GPIO extra für Pi4/älter setzen
          ansible.builtin.set_fact:
            gpio_extra: "pi4"
          when: "'Raspberry Pi 5' not in pi_model.stdout"

        # Install GPIO dependencies via uv extras
        - name: UV Sync mit GPIO extra ({{ gpio_extra }})
          ansible.builtin.command:
            cmd: "/usr/local/bin/uv sync --extra {{ gpio_extra }}"
            chdir: "{{ project_dir }}"
          become: yes
          become_user: "{{ ansible_user }}"
          environment:
            PATH: "/usr/local/bin:/usr/bin:/bin"

        # System gpiod tools (useful for debugging)
        - name: gpiod CLI tools installieren
          ansible.builtin.apt:
            pkg:
              - gpiod
            state: present
      tags: gpio

  handlers:
    - name: Reboot Raspberry Pi
      ansible.builtin.reboot:
