---
- name: Setup Raspberry Pi 5 für E-Nose Projekt (Full Stack)
  hosts: raspi
  become: yes
  vars:
    project_dir: "/home/{{ ansible_user }}/e-nose-project"
    # --- InfluxDB Konfiguration ---
    influx_user: "admin"
    influx_password: "enose_secret_password"  # Nach Setup ändern!
    influx_org: "enose_org"
    influx_bucket: "sensor_data"
    influx_retention: "300d"

  tasks:
    # ---------------------------------------------------------
    # 1. System-Grundlagen
    # ---------------------------------------------------------
    - name: System-Pakete aktualisieren
      apt:
        update_cache: yes
        upgrade: dist

    - name: Notwendige System-Pakete installieren
      apt:
        pkg:
          - i2c-tools
          - python3-venv
          - python3-pip
          - python3-dev
          - build-essential
          - libatlas-base-dev
          - wget
          - gpg
        state: present

    # ---------------------------------------------------------
    # 2. InfluxDB Installation & Setup
    # ---------------------------------------------------------
    - name: InfluxDB GPG Key herunterladen
      get_url:
        url: https://repos.influxdata.com/influxdata-archive_compat.key
        dest: /tmp/influxdata-archive_compat.key
        mode: '0644'

    - name: InfluxDB GPG Keyring erstellen
      shell: |
        cat /tmp/influxdata-archive_compat.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
      args:
        creates: /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg

    - name: InfluxDB Repository hinzufügen
      lineinfile:
        path: /etc/apt/sources.list.d/influxdata.list
        line: 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main'
        create: yes
        state: present

    - name: Paketquellen aktualisieren (nach Repo-Add)
      apt:
        update_cache: yes

    - name: InfluxDB & CLI installieren
      apt:
        pkg:
          - influxdb2
          - influxdb2-cli
        state: present

    - name: InfluxDB Service starten und aktivieren
      service:
        name: influxdb
        state: started
        enabled: yes

    - name: Warte auf InfluxDB Start
      wait_for:
        port: 8086
        delay: 5

    # --- Automatisches DB-Setup (Idempotent durch Check auf Credentials Datei) ---

    - name: Prüfen ob Setup bereits lief (Credentials Datei existiert)
      stat:
        path: "{{ project_dir }}/INFLUX_CREDENTIALS.md"
      register: cred_file

    - name: InfluxDB Setup ausführen (nur wenn noch nicht konfiguriert)
      command: >
        influx setup 
        --username "{{ influx_user }}" 
        --password "{{ influx_password }}" 
        --org "{{ influx_org }}" 
        --bucket "{{ influx_bucket }}" 
        --retention "{{ influx_retention }}" 
        --force
      when: not cred_file.stat.exists
      register: setup_output
      ignore_errors: yes # Falls DB schon konfiguriert ist, aber File fehlt

    - name: Admin Token abrufen
      shell: |
        influx auth list --user "{{ influx_user }}" --hide-headers | cut -f 4
      register: admin_token
      changed_when: false

    - name: Projekt-Verzeichnis erstellen (falls nicht existent)
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Credentials Datei erstellen
      copy:
        dest: "{{ project_dir }}/INFLUX_CREDENTIALS.md"
        owner: "{{ ansible_user }}"
        content: |
          # InfluxDB Zugangsdaten
          Generiert durch Ansible am: {{ ansible_date_time.iso8601 }}

          ## Login Details
          - **URL:** http://localhost:8086
          - **Username:** {{ influx_user }}
          - **Password:** {{ influx_password }}
          - **Organization:** {{ influx_org }}
          - **Bucket:** {{ influx_bucket }}

          ## API Token (WICHTIG FÜR PYTHON SKRIPT!)
          ```
          {{ admin_token.stdout }}
          ```
          
          > Bitte kopiere diesen Token in dein Python-Skript (logic.py / main.py).

    # ---------------------------------------------------------
    # 3. Hardware Konfiguration (I2C)
    # ---------------------------------------------------------
    - name: I2C aktivieren (boot config)
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^dtparam=i2c_arm='
        line: 'dtparam=i2c_arm=on'
        state: present
      notify: Reboot Raspberry Pi

    - name: I2C Kernel Module laden
      modprobe:
        name: i2c-dev
        state: present

    # ---------------------------------------------------------
    # 4. Python Umgebung
    # ---------------------------------------------------------
    - name: Python Virtual Environment erstellen
      command:
        cmd: python3 -m venv venv
        creates: "{{ project_dir }}/venv"
      args:
        chdir: "{{ project_dir }}"
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Python Dependencies installieren
      pip:
        virtualenv: "{{ project_dir }}/venv"
        name:
          - adafruit-circuitpython-bme680
          - pandas
          - numpy
          - scikit-learn
          - joblib
          - RPi.GPIO
          - influxdb-client
      become: yes
      become_user: "{{ ansible_user }}"

    - name: User zur i2c Gruppe hinzufügen
      user:
        name: "{{ ansible_user }}"
        groups: i2c,gpio
        append: yes

  handlers:
    - name: Reboot Raspberry Pi
      reboot: